# Generated by Django 4.0 on 2022-12-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Name',
            new_name='MOdel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Date',
        ),
        migrations.AddField(
            model_name='car',
            name='Marka',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='Yil',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
