# Generated by Django 4.0 on 2022-12-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_name_car_model_remove_car_date_car_marka_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='MOdel',
            new_name='Model',
        ),
        migrations.AlterField(
            model_name='car',
            name='Yil',
            field=models.CharField(max_length=250),
        ),
    ]
