# Generated by Django 4.0 on 2023-01-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movie', '0003_rename_model_car_model_alter_car_yil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='User_ID',
            new_name='Users_ID',
        ),
        migrations.RenameField(
            model_name='musteri',
            old_name='User_ID',
            new_name='Users_ID',
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='Yil',
            field=models.DateField(),
        ),
    ]
