# Generated by Django 4.0 on 2023-01-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_user_users_rename_user_id_contact_us_users_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user',
            new_name='user_id',
        ),
    ]
