# Generated by Django 4.0 on 2023-01-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_user_car_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Musteri_ID',
        ),
    ]
