# Generated by Django 4.0 on 2023-01-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_car_musteri_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user_id',
            new_name='user',
        ),
    ]
