# Generated by Django 4.0 on 2023-01-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rename_user_id_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='OtoTamir_ID',
        ),
        migrations.RemoveField(
            model_name='adres',
            name='Musteri_ID',
        ),
        migrations.RemoveField(
            model_name='adres',
            name='Person_ID',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Servis_ID',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='Users_ID',
        ),
        migrations.RemoveField(
            model_name='furnitures',
            name='Servis_ID',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='Users_ID',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Servis_ID',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='Musteri_ID',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Adres',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Contact_us',
        ),
        migrations.DeleteModel(
            name='Furnitures',
        ),
        migrations.DeleteModel(
            name='Musteri',
        ),
        migrations.DeleteModel(
            name='OtoTamir',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Servis',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
