# Generated by Django 4.0 on 2023-01-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Musteri_ID',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Servis_ID',
        ),
    ]
