# Generated by Django 4.0 on 2023-01-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_car_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
